# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EEGEnvironmentWindow(object):
    def setupUi(self, EEGEnvironmentWindow):
        EEGEnvironmentWindow.setObjectName("EEGEnvironmentWindow")
        EEGEnvironmentWindow.setEnabled(True)
        EEGEnvironmentWindow.resize(1250, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EEGEnvironmentWindow.sizePolicy().hasHeightForWidth())
        EEGEnvironmentWindow.setSizePolicy(sizePolicy)
        EEGEnvironmentWindow.setMinimumSize(QtCore.QSize(1250, 0))
        EEGEnvironmentWindow.setMaximumSize(QtCore.QSize(1250, 720))
        self.centralwidget = QtWidgets.QWidget(EEGEnvironmentWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.bottomHBoxLayout = QtWidgets.QHBoxLayout()
        self.bottomHBoxLayout.setObjectName("bottomHBoxLayout")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setObjectName("addButton")
        self.bottomHBoxLayout.addWidget(self.addButton)
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setMinimumSize(QtCore.QSize(51, 0))
        self.deleteButton.setObjectName("deleteButton")
        self.bottomHBoxLayout.addWidget(self.deleteButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottomHBoxLayout.addItem(spacerItem)
        self.loadFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadFileButton.setObjectName("loadFileButton")
        self.bottomHBoxLayout.addWidget(self.loadFileButton)
        self.signInButton = QtWidgets.QPushButton(self.centralwidget)
        self.signInButton.setObjectName("signInButton")
        self.bottomHBoxLayout.addWidget(self.signInButton)
        self.gridLayout.addLayout(self.bottomHBoxLayout, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 2044, 611))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.allSubjectsLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.allSubjectsLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.allSubjectsLayout.setContentsMargins(0, 0, 0, 0)
        self.allSubjectsLayout.setObjectName("allSubjectsLayout")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        EEGEnvironmentWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EEGEnvironmentWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1250, 22))
        self.menubar.setObjectName("menubar")
        EEGEnvironmentWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EEGEnvironmentWindow)
        self.statusbar.setObjectName("statusbar")
        EEGEnvironmentWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EEGEnvironmentWindow)
        QtCore.QMetaObject.connectSlotsByName(EEGEnvironmentWindow)

    def retranslateUi(self, EEGEnvironmentWindow):
        _translate = QtCore.QCoreApplication.translate
        EEGEnvironmentWindow.setWindowTitle(_translate("EEGEnvironmentWindow", "EEG Environment"))
        self.addButton.setText(_translate("EEGEnvironmentWindow", "+"))
        self.deleteButton.setText(_translate("EEGEnvironmentWindow", "-"))
        self.loadFileButton.setText(_translate("EEGEnvironmentWindow", "Load file"))
        self.signInButton.setText(_translate("EEGEnvironmentWindow", "Sign in"))
